/*
 * ============================================================
 * kw-pdf-edit English Patch
 * Version: 1.1
 * Updated: 2026-09-26
 * ============================================================
 *
 * English localization patch for the kw-pdf-edit Kintone plugin.
 *
 * Desktop + Kintone Mobile App / Android WebView support.
 *
 * This patch translates Japanese UI text generated by kw-pdf-edit
 * without modifying Kintone record data or attached PDF files.
 *
 * Handles:
 * - Visible text
 * - Button/tool titles
 * - aria-label accessibility text
 * - Placeholders / alt text
 * - Dynamically created plugin controls
 * - Dynamic "[filename] を編集する" labels
 * - Rapidly rebuilt mobile/WebView plugin UI
 *
 * IMPORTANT:
 * Actual attachment filenames are intentionally NOT renamed.
 * ============================================================
 */

(function () {
  'use strict';

  const PATCH_NAME = 'kw-pdf-edit English Patch';
  const PATCH_VERSION = '1.1';

  /*
   * ============================================================
   * TRANSLATIONS
   * ============================================================
   */

  const translations = {

    // File controls
    'ファイルをダウンロード': 'Download File',

    // System fields
    '（システム）自動保存フラグ': '(System) Autosave Flag',
    '（システム）自動保存日時': '(System) Autosave Date/Time',

    // Page / viewer controls
    '前のページ': 'Previous Page',
    '次のページ': 'Next Page',
    '縮小': 'Zoom Out',
    '拡大': 'Zoom In',
    '全画面': 'Full Screen',
    'ウィンドウいっぱいに広げる': 'Fit to Window',
    '閉じる': 'Close',
    '標準': 'Actual Size',
    '元の大きさに戻す': 'Restore Original Size',

    // Main editing tools
    '選択': 'Select',
    '手のひら': 'Hand',
    'サイン': 'Signature',
    '画像': 'Image',
    '手書き': 'Freehand',
    'テキスト': 'Text',
    '図形': 'Shape',
    '矢印': 'Arrow',
    '墨消し': 'Redact',

    // Editing actions
    '↶ 元に戻す': '↶ Undo',
    '↷ やり直す': '↷ Redo',
    '選択を削除': 'Delete Selection',
    '背面へ': 'Send to Back',
    '前面へ': 'Bring to Front',
    '保存する': 'Save',

    // Editing instructions
    '配置済みのものをクリックすると、色・太さ・塗り・形をあとから直せます（どのツールを選んでいても、ダブルクリックで直接つかめます）。':
      'Click an existing object to change its color, thickness, fill, or shape. You can also double-click an object to select it directly, regardless of the active tool.',

    '消したい範囲をドラッグしてください。保存時に 150dpi で焼き直し、元の文字・画像をファイルから削除します（取り消せません）。':
      'Drag over the area you want to redact. When saved, the page will be flattened at 150 dpi and the original text and images will be permanently removed. This cannot be undone.',

    'ここでの設定は「次に描くもの」に使われます。配置済みのものは「選択」ツール（またはダブルクリック）で直せます。':
      'These settings apply to the next object you draw. To modify an existing object, use the Select tool or double-click it.',

    'ドラッグでページを動かせます。ほかのツールを選んでいるときも、Space を押している間・マウス中ボタンのドラッグで動かせます（Ctrl＋ホイールで拡大縮小）。':
      'Drag to move the page. While using another tool, hold Space or drag with the middle mouse button to move the page. Use Ctrl + mouse wheel to zoom.',

    // General properties
    '色': 'Color',
    '色を選ぶ': 'Choose Color',
    '太さ': 'Thickness',
    '始点': 'Start',
    '終点': 'End',
    '形': 'Shape',

    // Shapes
    '四角': 'Rectangle',
    '角丸四角': 'Rounded Rectangle',
    '円': 'Ellipse',
    '三角': 'Triangle',
    'ひし形': 'Diamond',
    'マーカー': 'Marker',
    'チェック': 'Check',
    'バツ': 'X',
    '多角形': 'Polygon',

    // Shape properties
    '枠線': 'Border',
    '枠線の太さ': 'Border Thickness',
    '塗り': 'Fill',
    'なし': 'None',

    // Text properties
    '書体': 'Font',
    'ゴシック': 'Sans Serif',
    '明朝': 'Serif',
    '文字サイズ': 'Font Size',
    '文字色': 'Text Color',
    '行揃え': 'Alignment',
    '左': 'Left',
    '中央': 'Center',
    '右': 'Right',

    // Font loading
    'フォントを読み込んでいます…': 'Loading font...',
    '日本語フォントを読み込んでいます…':
      'Loading Japanese font...',

    // Freehand
    'ペンの色': 'Pen Color',
    '直前のストロークを消す': 'Undo Last Stroke',

    // Images
    '登録画像': 'Saved Images',
    'パソコンから画像を選ぶ':
      'Choose Image from Computer',

    '画像を置いたあと、四隅で拡大縮小・上のハンドルで回転できます。':
      'After placing an image, use the corner handles to resize it and the top handle to rotate it.',

    // Signature
    'サインを書く': 'Add Signature',

    '「サインを書く」を押すと、画面いっぱいの欄に大きく書けます。書いたサインはすぐページに表示されます。':
      'Select Add Signature to sign in a full-screen area. Your signature will appear on the page immediately.',

    'サインをお願いします': 'Please Sign',
    'キャンセル': 'Cancel',
    'サインを書く欄': 'Signature Area',

    'この枠の中に、指またはタッチペンで大きくサインしてください':
      'Sign inside this box using your finger or stylus.',

    // Signature colors
    '黒': 'Black',
    '濃紺': 'Dark Blue',

    // Signature thickness
    '太さ 2': 'Thickness 2',
    '太さ 3': 'Thickness 3',
    '太さ 4': 'Thickness 4',
    '太さ 6': 'Thickness 6',

    // Signature actions
    '1画消す': 'Undo Last Stroke',
    '全部消す': 'Clear All',
    'このサインを使う': 'Use This Signature',

    // Status messages
    'ファイルを読み込んでいます…': 'Loading File...',
    'ページを描画しています…': 'Rendering Page...',

    // Dialogs
    '変更がありません': 'No Changes',

    '書き加えたものがありません。ページに何か配置してから保存してください。':
      'There are no changes to save. Add something to the page before saving.'
  };


  /*
   * ============================================================
   * HELPERS
   * ============================================================
   */

  const JP_REGEX =
    /[\u3040-\u30ff\u3400-\u9fff]/;


  function hasJapanese(value) {
    return JP_REGEX.test(
      String(value || '')
    );
  }


  function isKwPdfElement(element) {

    if (
      !element ||
      element.nodeType !== Node.ELEMENT_NODE
    ) {
      return false;
    }

    try {

      if (
        String(element.className || '')
          .includes('kwpe-')
      ) {
        return true;
      }

      if (
        element.closest &&
        element.closest('[class*="kwpe-"]')
      ) {
        return true;
      }

    } catch (e) {
      // Ignore DOM/WebView lookup errors.
    }

    return false;
  }


  /*
   * ============================================================
   * STRING TRANSLATION
   * ============================================================
   */

  function translateString(value) {

    if (typeof value !== 'string') {
      return value;
    }

    const trimmed = value.trim();

    if (
      !trimmed ||
      !hasJapanese(trimmed)
    ) {
      return value;
    }


    /*
     * Exact translation.
     */
    if (
      Object.prototype.hasOwnProperty.call(
        translations,
        trimmed
      )
    ) {

      return value.replace(
        trimmed,
        translations[trimmed]
      );
    }


    /*
     * Dynamic filename edit label.
     *
     * Example:
     *
     * example.pdf を編集する
     *
     * becomes:
     *
     * Edit example.pdf
     *
     * This changes the UI label only.
     * The actual attachment filename is untouched.
     */

    const editFileMatch =
      trimmed.match(/^(.+?)\s*を編集する$/);

    if (editFileMatch) {

      const filename =
        editFileMatch[1];

      return `Edit ${filename}`;
    }


    return value;
  }


  /*
   * ============================================================
   * TEXT NODE TRANSLATION
   * ============================================================
   */

  function translateTextNode(node) {

    if (
      !node ||
      node.nodeType !== Node.TEXT_NODE
    ) {
      return;
    }

    const parent =
      node.parentElement;

    if (!parent) {
      return;
    }

    if (
      [
        'SCRIPT',
        'STYLE',
        'NOSCRIPT'
      ].includes(parent.tagName)
    ) {
      return;
    }


    const original =
      node.nodeValue;

    if (!hasJapanese(original)) {
      return;
    }


    const trimmed =
      String(original || '').trim();


    /*
     * Exact known translations can be safely translated
     * regardless of whether Kintone itself supplied the
     * surrounding wrapper.
     *
     * This is important on mobile because the two system
     * fields use native Kintone H3 labels rather than
     * kwpe-* classes.
     */

    if (
      Object.prototype.hasOwnProperty.call(
        translations,
        trimmed
      )
    ) {

      node.nodeValue =
        original.replace(
          trimmed,
          translations[trimmed]
        );

      return;
    }


    /*
     * Unknown/dynamic translation patterns remain
     * restricted to kw-pdf-edit elements.
     */

    if (!isKwPdfElement(parent)) {
      return;
    }


    const translated =
      translateString(original);

    if (translated !== original) {
      node.nodeValue = translated;
    }
  }


  /*
   * ============================================================
   * ATTRIBUTE TRANSLATION
   * ============================================================
   */

  const translatedAttributes = [
    'title',
    'aria-label',
    'placeholder',
    'alt'
  ];


  function translateAttributes(element) {

    if (
      !element ||
      element.nodeType !== Node.ELEMENT_NODE
    ) {
      return;
    }


    translatedAttributes.forEach(
      function (attribute) {

        let original = null;

        try {

          original =
            element.getAttribute(attribute);

        } catch (e) {

          return;
        }


        if (
          !original ||
          !hasJapanese(original)
        ) {
          return;
        }


        const trimmed =
          original.trim();


        /*
         * Exact translation.
         */

        if (
          Object.prototype.hasOwnProperty.call(
            translations,
            trimmed
          )
        ) {

          element.setAttribute(
            attribute,
            original.replace(
              trimmed,
              translations[trimmed]
            )
          );

          return;
        }


        /*
         * Dynamic labels are limited to kw-pdf-edit.
         */

        if (!isKwPdfElement(element)) {
          return;
        }


        const translated =
          translateString(original);


        if (translated !== original) {

          element.setAttribute(
            attribute,
            translated
          );
        }

      }
    );
  }


  /*
   * ============================================================
   * ELEMENT TRANSLATION
   * ============================================================
   */

  function translateElement(element) {

    if (
      !element ||
      element.nodeType !== Node.ELEMENT_NODE
    ) {
      return;
    }


    translateAttributes(element);


    /*
     * Translate direct text nodes.
     */

    try {

      [...element.childNodes].forEach(
        function (node) {

          if (
            node.nodeType === Node.TEXT_NODE
          ) {
            translateTextNode(node);
          }

        }
      );

    } catch (e) {
      // Ignore transient mobile DOM errors.
    }
  }


  /*
   * ============================================================
   * TREE SCANNER
   * ============================================================
   */

  function scanTree(root) {

    if (!root) {
      return;
    }


    if (
      root.nodeType === Node.TEXT_NODE
    ) {

      translateTextNode(root);
      return;
    }


    /*
     * DocumentFragment is supported because some WebView/plugin
     * interfaces can be constructed inside fragments before being
     * attached to the document.
     */

    if (
      root.nodeType !== Node.ELEMENT_NODE &&
      root.nodeType !== Node.DOCUMENT_FRAGMENT_NODE
    ) {
      return;
    }


    if (
      root.nodeType === Node.ELEMENT_NODE
    ) {
      translateElement(root);
    }


    try {

      root
        .querySelectorAll('*')
        .forEach(translateElement);

    } catch (e) {
      // Ignore inaccessible/transient trees.
    }
  }


  /*
   * ============================================================
   * OPEN SHADOW ROOT SUPPORT
   * ============================================================
   *
   * Not currently shown by the diagnostic as the cause of the
   * mobile issue, but scanning open roots costs little and makes
   * the patch safer for future plugin versions.
   */

  function scanShadowRoots() {

    try {

      document
        .querySelectorAll('*')
        .forEach(
          function (element) {

            if (element.shadowRoot) {
              scanTree(element.shadowRoot);
            }

          }
        );

    } catch (e) {
      // Ignore inaccessible roots.
    }
  }


  /*
   * ============================================================
   * FULL SCAN
   * ============================================================
   */

  function fullScan() {

    if (!document.body) {
      return;
    }

    scanTree(document.body);
    scanShadowRoots();
  }


  /*
   * ============================================================
   * MUTATION OBSERVER
   * ============================================================
   */

  let scanScheduled = false;


  function scheduleScan() {

    if (scanScheduled) {
      return;
    }

    scanScheduled = true;


    /*
     * setTimeout is deliberately used rather than relying only
     * on requestAnimationFrame.
     *
     * Android WebViews can throttle animation frames differently
     * while dialogs/tool panels are being constructed.
     */

    setTimeout(
      function () {

        scanScheduled = false;
        fullScan();

      },
      25
    );
  }


  const observer =
    new MutationObserver(
      function (mutations) {

        mutations.forEach(
          function (mutation) {

            /*
             * Newly inserted UI.
             */

            if (
              mutation.type === 'childList'
            ) {

              mutation.addedNodes.forEach(
                function (node) {

                  if (
                    node.nodeType === Node.TEXT_NODE
                  ) {

                    translateTextNode(node);

                  } else if (
                    node.nodeType === Node.ELEMENT_NODE ||
                    node.nodeType === Node.DOCUMENT_FRAGMENT_NODE
                  ) {

                    scanTree(node);

                  }

                }
              );
            }


            /*
             * Existing text changed.
             */

            if (
              mutation.type === 'characterData'
            ) {

              translateTextNode(
                mutation.target
              );
            }


            /*
             * Relevant attribute changed.
             */

            if (
              mutation.type === 'attributes'
            ) {

              translateAttributes(
                mutation.target
              );
            }

          }
        );


        /*
         * Deferred backup scan after each mutation batch.
         */

        scheduleScan();

      }
    );


  /*
   * ============================================================
   * MOBILE / WEBVIEW BACKUP SWEEP
   * ============================================================
   *
   * The mobile diagnostic showed that kw-pdf-edit can rapidly
   * construct and replace its editor interface inside the
   * Kintone Android WebView.
   *
   * The MutationObserver remains the primary translator.
   *
   * This low-frequency sweep is a safety net for controls that
   * are reconstructed between observer passes or altered by the
   * plugin immediately after insertion.
   *
   * It is intentionally lightweight and only performs the same
   * Japanese-text checks already used by the normal scanner.
   */

  let backupSweep = null;


  function startBackupSweep() {

    if (backupSweep) {
      return;
    }


    backupSweep =
      setInterval(
        function () {

          /*
           * Avoid unnecessary work when there is no Japanese
           * text anywhere in the current page.
           */

          let bodyText = '';

          try {
            bodyText =
              document.body
                ? document.body.textContent
                : '';
          } catch (e) {
            bodyText = '';
          }


          /*
           * We also scan if kwpe elements exist because some
           * untranslated Japanese may exist only in title or
           * aria-label attributes and therefore not body text.
           */

          let hasKwpe = false;

          try {

            hasKwpe =
              !!document.querySelector(
                '[class*="kwpe-"]'
              );

          } catch (e) {
            hasKwpe = false;
          }


          if (
            hasJapanese(bodyText) ||
            hasKwpe
          ) {
            fullScan();
          }

        },
        750
      );
  }


  /*
   * ============================================================
   * START PATCH
   * ============================================================
   */

  let started = false;


  function startPatch() {

    if (
      started ||
      !document.body
    ) {
      return;
    }

    started = true;


    /*
     * Initial translation.
     */

    fullScan();


    /*
     * Watch future UI changes.
     */

    observer.observe(
      document.body,
      {
        childList: true,
        subtree: true,
        characterData: true,
        attributes: true,
        attributeFilter:
          translatedAttributes
      }
    );


    /*
     * Mobile/WebView safety sweep.
     */

    startBackupSweep();


    /*
     * A few delayed startup scans catch plugin controls that
     * initialize immediately after Kintone customization JS.
     */

    setTimeout(fullScan, 100);
    setTimeout(fullScan, 500);
    setTimeout(fullScan, 1500);
    setTimeout(fullScan, 3000);


    console.log(
      `[${PATCH_NAME}] Version ${PATCH_VERSION} loaded`
    );
  }


  /*
   * ============================================================
   * INITIALIZATION
   * ============================================================
   */

  if (document.body) {

    startPatch();

  } else {

    document.addEventListener(
      'DOMContentLoaded',
      startPatch,
      {
        once: true
      }
    );

  }

})();
