/*
 * ============================================================
 * kw-pdf-edit English Patch
 * Version: 1.0
 * Updated: 2026-09-25
 * ============================================================
 *
 * English localization patch for the kw-pdf-edit Kintone plugin.
 *
 * This patch translates Japanese UI text generated by kw-pdf-edit
 * without modifying Kintone record data or attached PDF files.
 *
 * Handles:
 * - Visible text
 * - Button/tool titles
 * - aria-label accessibility text
 * - Placeholders / alt text
 * - Dynamically created plugin controls
 * - Dynamic "[filename] を編集する" labels
 *
 * IMPORTANT:
 * Actual attachment filenames are intentionally NOT renamed.
 * ============================================================
 */

(function () {
  'use strict';

  const PATCH_NAME = 'kw-pdf-edit English Patch';
  const PATCH_VERSION = '1.0';

  /*
   * ============================================================
   * TRANSLATIONS
   * ============================================================
   */

  const translations = {

    /*
     * File controls
     */
    'ファイルをダウンロード': 'Download File',

    /*
     * System fields
     */
    '（システム）自動保存フラグ': '(System) Autosave Flag',
    '（システム）自動保存日時': '(System) Autosave Date/Time',

    /*
     * Page / viewer controls
     */
    '前のページ': 'Previous Page',
    '次のページ': 'Next Page',
    '縮小': 'Zoom Out',
    '拡大': 'Zoom In',
    '全画面': 'Full Screen',
    'ウィンドウいっぱいに広げる': 'Fit to Window',
    '閉じる': 'Close',
    '標準': 'Actual Size',
    '元の大きさに戻す': 'Restore Original Size',

    /*
     * Main editing tools
     */
    '選択': 'Select',
    '手のひら': 'Hand',
    'サイン': 'Signature',
    '画像': 'Image',
    '手書き': 'Freehand',
    'テキスト': 'Text',
    '図形': 'Shape',
    '矢印': 'Arrow',
    '墨消し': 'Redact',

    /*
     * Editing actions
     */
    '↶ 元に戻す': '↶ Undo',
    '↷ やり直す': '↷ Redo',
    '選択を削除': 'Delete Selection',
    '背面へ': 'Send to Back',
    '前面へ': 'Bring to Front',
    '保存する': 'Save',

    /*
     * Editing instructions
     */
    '配置済みのものをクリックすると、色・太さ・塗り・形をあとから直せます（どのツールを選んでいても、ダブルクリックで直接つかめます）。':
      'Click an existing object to change its color, thickness, fill, or shape. You can also double-click an object to select it directly, regardless of the active tool.',

    '消したい範囲をドラッグしてください。保存時に 150dpi で焼き直し、元の文字・画像をファイルから削除します（取り消せません）。':
      'Drag over the area you want to redact. When saved, the page will be flattened at 150 dpi and the original text and images will be permanently removed. This cannot be undone.',

    'ここでの設定は「次に描くもの」に使われます。配置済みのものは「選択」ツール（またはダブルクリック）で直せます。':
      'These settings apply to the next object you draw. To modify an existing object, use the Select tool or double-click it.',

    /*
     * General properties
     */
    '色': 'Color',
    '色を選ぶ': 'Choose Color',
    '太さ': 'Thickness',
    '始点': 'Start',
    '終点': 'End',
    '形': 'Shape',

    /*
     * Shapes
     */
    '四角': 'Rectangle',
    '角丸四角': 'Rounded Rectangle',
    '円': 'Ellipse',
    '三角': 'Triangle',
    'ひし形': 'Diamond',
    'マーカー': 'Marker',
    'チェック': 'Check',
    'バツ': 'X',
    '多角形': 'Polygon',

    /*
     * Shape properties
     */
    '枠線': 'Border',
    '枠線の太さ': 'Border Thickness',
    '塗り': 'Fill',
    'なし': 'None',

    /*
     * Text properties
     */
    '書体': 'Font',
    'ゴシック': 'Sans Serif',
    '明朝': 'Serif',
    '文字サイズ': 'Font Size',
    '文字色': 'Text Color',
    '行揃え': 'Alignment',
    '左': 'Left',
    '中央': 'Center',
    '右': 'Right',

    /*
     * Font loading
     */
    'フォントを読み込んでいます…': 'Loading font...',
    '日本語フォントを読み込んでいます…':
      'Loading Japanese font...',

    /*
     * Freehand
     */
    'ペンの色': 'Pen Color',
    '直前のストロークを消す': 'Undo Last Stroke',

    /*
     * Images
     */
    '登録画像': 'Saved Images',
    'パソコンから画像を選ぶ':
      'Choose Image from Computer',

    '画像を置いたあと、四隅で拡大縮小・上のハンドルで回転できます。':
      'After placing an image, use the corner handles to resize it and the top handle to rotate it.',

    /*
     * Signature
     */
    'サインを書く': 'Add Signature',

    '「サインを書く」を押すと、画面いっぱいの欄に大きく書けます。書いたサインはすぐページに表示されます。':
      'Select Add Signature to sign in a full-screen area. Your signature will appear on the page immediately.',

    'サインをお願いします': 'Please Sign',
    'キャンセル': 'Cancel',
    'サインを書く欄': 'Signature Area',

    'この枠の中に、指またはタッチペンで大きくサインしてください':
      'Sign inside this box using your finger or stylus.',

    /*
     * Signature colors
     */
    '黒': 'Black',
    '濃紺': 'Dark Blue',

    /*
     * Signature thickness
     */
    '太さ 2': 'Thickness 2',
    '太さ 3': 'Thickness 3',
    '太さ 4': 'Thickness 4',
    '太さ 6': 'Thickness 6',

    /*
     * Signature actions
     */
    '1画消す': 'Undo Last Stroke',
    '全部消す': 'Clear All',
    'このサインを使う': 'Use This Signature',

    /*
     * Status messages
     */
    'ページを描画しています…': 'Rendering Page...'
  };


  /*
   * ============================================================
   * HELPERS
   * ============================================================
   */

  function hasJapanese(value) {
    return /[\u3040-\u30ff\u3400-\u9fff]/.test(
      String(value || '')
    );
  }


  /*
   * Determine whether an element belongs to kw-pdf-edit.
   *
   * Most plugin-generated elements use kwpe-* classes.
   *
   * Some Kintone field labels used by the plugin do not, so
   * known exact translations are still allowed separately.
   */
  function isKwPdfElement(element) {

    if (!element || element.nodeType !== Node.ELEMENT_NODE) {
      return false;
    }

    if (
      String(element.className || '').includes('kwpe-')
    ) {
      return true;
    }

    if (
      element.closest &&
      element.closest(
        '[class*="kwpe-"]'
      )
    ) {
      return true;
    }

    return false;
  }


  /*
   * ============================================================
   * TRANSLATE STRING
   * ============================================================
   */

  function translateString(value) {

    if (typeof value !== 'string') {
      return value;
    }

    const trimmed = value.trim();

    if (!trimmed || !hasJapanese(trimmed)) {
      return value;
    }


    /*
     * Exact translation
     */
    if (
      Object.prototype.hasOwnProperty.call(
        translations,
        trimmed
      )
    ) {

      return value.replace(
        trimmed,
        translations[trimmed]
      );
    }


    /*
     * ----------------------------------------------------------
     * Dynamic filename edit label
     * ----------------------------------------------------------
     *
     * Example:
     *
     * document.pdf を編集する
     *
     * becomes:
     *
     * Edit document.pdf
     *
     * This changes only UI labels such as title/aria-label.
     * It does NOT rename the file.
     */

    const editFileMatch =
      trimmed.match(/^(.+?)\s*を編集する$/);


    if (editFileMatch) {

      const filename = editFileMatch[1];

      return `Edit ${filename}`;
    }


    return value;
  }


  /*
   * ============================================================
   * TEXT NODE TRANSLATION
   * ============================================================
   */

  function translateTextNode(node) {

    if (
      !node ||
      node.nodeType !== Node.TEXT_NODE
    ) {
      return;
    }

    const parent = node.parentElement;

    if (!parent) {
      return;
    }


    if (
      ['SCRIPT', 'STYLE', 'NOSCRIPT'].includes(
        parent.tagName
      )
    ) {
      return;
    }


    const original = node.nodeValue;

    if (!hasJapanese(original)) {
      return;
    }


    const trimmed =
      String(original || '').trim();


    /*
     * Exact known translations are safe.
     */
    if (
      Object.prototype.hasOwnProperty.call(
        translations,
        trimmed
      )
    ) {

      node.nodeValue =
        original.replace(
          trimmed,
          translations[trimmed]
        );

      return;
    }


    /*
     * Dynamic translations should only be applied to
     * kw-pdf-edit elements.
     */
    if (!isKwPdfElement(parent)) {
      return;
    }


    const translated =
      translateString(original);


    if (translated !== original) {
      node.nodeValue = translated;
    }
  }


  /*
   * ============================================================
   * ATTRIBUTE TRANSLATION
   * ============================================================
   */

  const translatedAttributes = [
    'title',
    'aria-label',
    'placeholder',
    'alt'
  ];


  function translateAttributes(element) {

    if (
      !element ||
      element.nodeType !== Node.ELEMENT_NODE
    ) {
      return;
    }


    translatedAttributes.forEach(
      (attribute) => {

        const original =
          element.getAttribute(attribute);


        if (
          !original ||
          !hasJapanese(original)
        ) {
          return;
        }


        const trimmed =
          original.trim();


        /*
         * Known exact translation
         */
        if (
          Object.prototype.hasOwnProperty.call(
            translations,
            trimmed
          )
        ) {

          element.setAttribute(
            attribute,
            original.replace(
              trimmed,
              translations[trimmed]
            )
          );

          return;
        }


        /*
         * Dynamic labels are limited to kw-pdf-edit.
         */
        if (!isKwPdfElement(element)) {
          return;
        }


        const translated =
          translateString(original);


        if (translated !== original) {

          element.setAttribute(
            attribute,
            translated
          );
        }

      }
    );
  }


  /*
   * ============================================================
   * ELEMENT TRANSLATION
   * ============================================================
   */

  function translateElement(element) {

    if (
      !element ||
      element.nodeType !== Node.ELEMENT_NODE
    ) {
      return;
    }


    translateAttributes(element);


    /*
     * Translate only direct text nodes here.
     *
     * Descendants are handled separately by scanTree().
     */
    [...element.childNodes].forEach(
      (node) => {

        if (
          node.nodeType === Node.TEXT_NODE
        ) {
          translateTextNode(node);
        }

      }
    );
  }


  /*
   * ============================================================
   * TREE SCANNER
   * ============================================================
   */

  function scanTree(root) {

    if (!root) {
      return;
    }


    if (
      root.nodeType === Node.TEXT_NODE
    ) {

      translateTextNode(root);
      return;
    }


    if (
      root.nodeType !== Node.ELEMENT_NODE
    ) {
      return;
    }


    translateElement(root);


    root
      .querySelectorAll('*')
      .forEach(
        translateElement
      );
  }


  /*
   * ============================================================
   * MUTATION OBSERVER
   * ============================================================
   *
   * kw-pdf-edit dynamically creates:
   *
   * - Viewer controls
   * - Tool panels
   * - Signature dialog
   * - Shape controls
   * - Tooltips
   * - Status messages
   *
   * The observer translates these as they appear.
   * ============================================================
   */

  let scanScheduled = false;


  function scheduleScan() {

    if (scanScheduled) {
      return;
    }


    scanScheduled = true;


    requestAnimationFrame(() => {

      scanScheduled = false;

      scanTree(document.body);

    });
  }


  const observer =
    new MutationObserver(
      (mutations) => {

        let needsScan = false;


        mutations.forEach(
          (mutation) => {

            /*
             * New elements/text
             */
            if (
              mutation.type === 'childList' &&
              mutation.addedNodes.length
            ) {

              mutation.addedNodes.forEach(
                (node) => {

                  if (
                    node.nodeType === Node.TEXT_NODE
                  ) {

                    translateTextNode(node);

                  } else if (
                    node.nodeType === Node.ELEMENT_NODE
                  ) {

                    scanTree(node);

                  }

                }
              );
            }


            /*
             * Existing text changed
             */
            if (
              mutation.type === 'characterData'
            ) {

              translateTextNode(
                mutation.target
              );
            }


            /*
             * Relevant attribute changed
             */
            if (
              mutation.type === 'attributes'
            ) {

              translateAttributes(
                mutation.target
              );
            }


            needsScan = true;
          }
        );


        /*
         * One deferred full scan catches elements that the
         * plugin builds over several rapid DOM mutations.
         */
        if (needsScan) {
          scheduleScan();
        }

      }
    );


  /*
   * ============================================================
   * START PATCH
   * ============================================================
   */

  function startPatch() {

    if (!document.body) {
      return;
    }


    /*
     * Initial translation
     */
    scanTree(document.body);


    /*
     * Watch future plugin UI changes
     */
    observer.observe(
      document.body,
      {
        childList: true,
        subtree: true,
        characterData: true,
        attributes: true,
        attributeFilter: translatedAttributes
      }
    );


    console.log(
      `[${PATCH_NAME}] Version ${PATCH_VERSION} loaded`
    );
  }


  /*
   * Kintone normally loads customization JS after the document
   * exists, but this makes the patch safe if it loads earlier.
   */

  if (document.body) {

    startPatch();

  } else {

    document.addEventListener(
      'DOMContentLoaded',
      startPatch,
      { once: true }
    );

  }

})();
