/*
 * KW Read Check English Patch
 * Version: 1.0
 * Updated: 2026-09-16
 *
 * KIZUNA Works - Read Check for kintone
 *
 * Translates Japanese UI text generated by the Read Check plugin.
 * Does NOT modify stored values or record data.
 */

(function () {
  'use strict';

  function translateReadCheck() {

    /*
     * ==========================================================
     * 1. READ CHECK SIDEBAR TAB
     *
     * 既読 -> Read
     * ==========================================================
     */

    const tab = document.querySelector('#kw-rdck-tab');

    if (tab) {

      // Visible text
      [...tab.childNodes].forEach((node) => {
        if (
          node.nodeType === Node.TEXT_NODE &&
          node.nodeValue.trim() === '既読'
        ) {
          node.nodeValue = node.nodeValue.replace(
            '既読',
            'Read'
          );
        }
      });

      // Tooltip/title
      if (tab.getAttribute('title') === '既読') {
        tab.setAttribute('title', 'Read');
      }
    }


    /*
     * ==========================================================
     * 2. NUMBER OF PEOPLE WHO READ THE RECORD
     *
     * 既読 1 名  -> Read by 1 person
     * 既読 2 名  -> Read by 2 people
     * 既読 15 名 -> Read by 15 people
     * ==========================================================
     */

    document.querySelectorAll(
      '.kw-rdck-sb-count'
    ).forEach((element) => {

      const text = element.textContent.trim();

      const match = text.match(
        /^既読\s*([\d,]+)\s*名$/
      );

      if (!match) {
        return;
      }

      const displayedCount = match[1];

      const count = Number(
        displayedCount.replace(/,/g, '')
      );

      element.textContent =
        count === 1
          ? `Read by ${displayedCount} person`
          : `Read by ${displayedCount} people`;

    });


    /*
     * ==========================================================
     * 3. FIRST READ DATE/TIME
     *
     * 初回 2026/09/16 17:09
     *
     * becomes:
     *
     * First read: 2026/09/16 17:09
     * ==========================================================
     */

    document.querySelectorAll(
      '.kw-rdck-reader-line'
    ).forEach((element) => {

      const text = element.textContent.trim();

      if (text.startsWith('初回')) {

        element.textContent = text.replace(
          /^初回\s*/,
          'First read: '
        );

        return;
      }


      /*
       * ========================================================
       * 4. LAST READ DATE/TIME
       *
       * 最終 2026/09/16 17:09
       *
       * becomes:
       *
       * Last read: 2026/09/16 17:09
       * ========================================================
       */

      if (text.startsWith('最終')) {

        element.textContent = text.replace(
          /^最終\s*/,
          'Last read: '
        );

      }

    });


    /*
     * ==========================================================
     * 5. INDIVIDUAL READ COUNT
     *
     * 既読 1 回  -> Read 1 time
     * 既読 2 回  -> Read 2 times
     * 既読 10 回 -> Read 10 times
     * ==========================================================
     */

    document.querySelectorAll(
      '.kw-rdck-reader-count'
    ).forEach((element) => {

      const text = element.textContent.trim();

      const match = text.match(
        /^既読\s*([\d,]+)\s*回$/
      );

      if (!match) {
        return;
      }

      const displayedCount = match[1];

      const count = Number(
        displayedCount.replace(/,/g, '')
      );

      element.textContent =
        count === 1
          ? `Read ${displayedCount} time`
          : `Read ${displayedCount} times`;

    });

  }


  /*
   * ============================================================
   * MUTATION OBSERVER
   * ============================================================
   *
   * Read Check dynamically creates/updates its sidebar.
   * Re-run the translator when the DOM changes.
   * ============================================================
   */

  let translationScheduled = false;

  const observer = new MutationObserver(() => {

    if (translationScheduled) {
      return;
    }

    translationScheduled = true;

    requestAnimationFrame(() => {

      translationScheduled = false;

      translateReadCheck();

    });

  });


  observer.observe(
    document.body,
    {
      childList: true,
      subtree: true
    }
  );


  /*
   * Initial translation
   */

  translateReadCheck();

})();
