/*
 * KW Read Check English Patch
 * Version: 1.1
 * Updated: 2026-09-16
 *
 * KIZUNA Works - Read Check for kintone
 *
 * Translates Japanese UI text generated by the Read Check plugin.
 * Does NOT modify stored values or record data.
 */

(function () {
  'use strict';

  function translateReadCheck() {

    /*
     * ==========================================================
     * 1. READ CHECK SIDEBAR TAB
     *
     * 既読 -> Read
     * ==========================================================
     */

    const tab = document.querySelector('#kw-rdck-tab');

    if (tab) {

      [...tab.childNodes].forEach((node) => {

        if (
          node.nodeType === Node.TEXT_NODE &&
          node.nodeValue.trim() === '既読'
        ) {
          node.nodeValue = node.nodeValue.replace(
            '既読',
            'Read'
          );
        }

      });

      if (tab.getAttribute('title') === '既読') {
        tab.setAttribute('title', 'Read');
      }
    }


    /*
     * ==========================================================
     * 2. NUMBER OF PEOPLE WHO READ THE RECORD
     *
     * 既読 1 名 -> Read by 1 person
     * 既読 2 名 -> Read by 2 people
     * ==========================================================
     */

    document.querySelectorAll(
      '.kw-rdck-sb-count'
    ).forEach((element) => {

      const text = element.textContent.trim();

      const match = text.match(
        /^既読\s*([\d,]+)\s*名$/
      );

      if (!match) {
        return;
      }

      const displayedCount = match[1];

      const count = Number(
        displayedCount.replace(/,/g, '')
      );

      element.textContent =
        count === 1
          ? `Read by ${displayedCount} person`
          : `Read by ${displayedCount} people`;

    });


    /*
     * ==========================================================
     * 3. READER INFORMATION LINES
     *
     * Handles:
     *
     * 初回 2026/09/16 17:09
     *
     * 最終 2026/09/16 17:17
     *
     * AND the combined form:
     *
     * 最終 2026/09/16 17:17既読 3 回
     *
     * OR after a previous translation:
     *
     * Last read: 2026/09/16 17:17既読 3 回
     * ==========================================================
     */

    document.querySelectorAll(
      '.kw-rdck-reader-line'
    ).forEach((element) => {

      let text = element.textContent.trim();


      /*
       * First read
       */

      if (text.startsWith('初回')) {

        text = text.replace(
          /^初回\s*/,
          'First read: '
        );

      }


      /*
       * Last read
       */

      if (text.startsWith('最終')) {

        text = text.replace(
          /^最終\s*/,
          'Last read: '
        );

      }


      /*
       * Read count contained inside reader line
       *
       * 既読 1 回 -> Read 1 time
       * 既読 3 回 -> Read 3 times
       */

      text = text.replace(
        /既読\s*([\d,]+)\s*回/g,
        (match, displayedCount) => {

          const count = Number(
            displayedCount.replace(/,/g, '')
          );

          return count === 1
            ? ` Read ${displayedCount} time`
            : ` Read ${displayedCount} times`;

        }
      );


      element.textContent = text;

    });


    /*
     * ==========================================================
     * 4. SEPARATE READ COUNT
     *
     * Kept for compatibility in case another plugin state
     * renders the count as its own element.
     *
     * 既読 1 回 -> Read 1 time
     * 既読 2 回 -> Read 2 times
     * ==========================================================
     */

    document.querySelectorAll(
      '.kw-rdck-reader-count'
    ).forEach((element) => {

      const text = element.textContent.trim();

      const match = text.match(
        /^既読\s*([\d,]+)\s*回$/
      );

      if (!match) {
        return;
      }

      const displayedCount = match[1];

      const count = Number(
        displayedCount.replace(/,/g, '')
      );

      element.textContent =
        count === 1
          ? `Read ${displayedCount} time`
          : `Read ${displayedCount} times`;

    });

  }


  /*
   * ============================================================
   * MUTATION OBSERVER
   * ============================================================
   */

  let translationScheduled = false;

  const observer = new MutationObserver(() => {

    if (translationScheduled) {
      return;
    }

    translationScheduled = true;

    requestAnimationFrame(() => {

      translationScheduled = false;

      translateReadCheck();

    });

  });


  observer.observe(
    document.body,
    {
      childList: true,
      subtree: true,
      characterData: true
    }
  );


  /*
   * ============================================================
   * INITIAL TRANSLATION
   * ============================================================
   */

  translateReadCheck();

})();
