/*
 * RIBBIT Fast Search English Patch
 * Version: 3.1
 * Updated: 2026-09-16
 */

(function () {
  'use strict';

  /*
   * ============================================================
   * RIBBIT Fast Search Plugin
   * English Display Text Patch
   * ============================================================
   *
   * Translates Japanese display text generated by the
   * RIBBIT Fast Search plugin.
   *
   * This patch:
   * - Changes visible text only
   * - Translates safe accessibility attributes
   * - Handles dynamically rendered RIBBIT elements
   * - Does NOT modify stored field values or record data
   * ============================================================
   */


  function replaceJapanesePluginText() {

    /*
     * ----------------------------------------------------------
     * 1. SIMPLE VISIBLE TEXT
     * ----------------------------------------------------------
     */

    const replacements = {
      'フィールドを検索': 'Search Fields',
      '表示件数': 'Items per page',
      '取得': 'Search',
      'クリア': 'Clear',
      'このフィールドはルックアップフィールドのコピー先に設定されているため、編集できません':
        'This field cannot be edited because it is configured as a destination field for a Lookup.'
    };


    const walker = document.createTreeWalker(
      document.body,
      NodeFilter.SHOW_TEXT,
      {
        acceptNode(node) {

          const parent = node.parentElement;

          if (!parent) {
            return NodeFilter.FILTER_REJECT;
          }

          // Never translate scripts, styles, etc.
          if (
            parent.tagName === 'SCRIPT' ||
            parent.tagName === 'STYLE' ||
            parent.tagName === 'NOSCRIPT'
          ) {
            return NodeFilter.FILTER_REJECT;
          }

          const text = String(node.nodeValue || '').trim();

          return replacements[text]
            ? NodeFilter.FILTER_ACCEPT
            : NodeFilter.FILTER_REJECT;
        }
      }
    );


    const nodes = [];

    while (walker.nextNode()) {
      nodes.push(walker.currentNode);
    }


    nodes.forEach((node) => {

      const text = String(node.nodeValue || '').trim();

      if (replacements[text]) {
        node.nodeValue = node.nodeValue.replace(
          text,
          replacements[text]
        );
      }

    });



    /*
     * ----------------------------------------------------------
     * 2. RECORD COUNT
     *
     * Handles:
     *
     * 件
     *
     * and:
     *
     * 1件
     * 25件
     * 1,613件
     * ----------------------------------------------------------
     */

    document.querySelectorAll('span.total').forEach((element) => {

      const text = element.textContent.trim();


      // Standalone 件
      if (text === '件') {
        element.textContent = 'records';
        return;
      }


      // Number + 件
      const countMatch = text.match(
        /^([\d,]+)\s*件$/
      );


      if (countMatch) {

        const displayedCount = countMatch[1];

        const numericCount = Number(
          displayedCount.replace(/,/g, '')
        );


        element.textContent =
          numericCount === 1
            ? `${displayedCount} record`
            : `${displayedCount} records`;

      }

    });



    /*
     * ----------------------------------------------------------
     * 3. OLD-STYLE LOCATION COUNTER
     *
     * Example:
     *
     * （1,364件中）
     *
     * becomes:
     *
     * (of 1,364 records)
     * ----------------------------------------------------------
     */

    document.querySelectorAll('.location').forEach(
      (locationElement) => {

        const text = locationElement.textContent;


        if (!text.includes('件中')) {
          return;
        }


        const match = text.match(
          /（([\d,]+)\s*件中）/
        );


        if (match) {

          const total = match[1];

          locationElement.textContent =
            locationElement.textContent.replace(
              /（[\d,]+\s*件中）/,
              ` (of ${total} records)`
            );

        }

      }
    );



    /*
     * ----------------------------------------------------------
     * 4. UNFILTERED TOTAL
     *
     * Examples:
     *
     * (全1,364件)
     * （全 1,364 件）
     *
     * becomes:
     *
     * (1,364 total records)
     * ----------------------------------------------------------
     */

    document.querySelectorAll(
      '.unfiltered-total'
    ).forEach((element) => {

      const text = element.textContent.trim();


      const totalMatch = text.match(
        /[（(]\s*全\s*([\d,]+)\s*件\s*[）)]/
      );


      if (totalMatch) {

        const displayedTotal = totalMatch[1];

        element.textContent =
          `(${displayedTotal} total records)`;

      }

    });



    /*
     * ----------------------------------------------------------
     * 5. ARIA-LABEL TRANSLATIONS
     * ----------------------------------------------------------
     */

    document.querySelectorAll(
      '[aria-label]'
    ).forEach((element) => {

      const label = element.getAttribute(
        'aria-label'
      );


      if (!label) {
        return;
      }



      /*
       * Add New Record
       *
       * 新規レコード追加
       */

      if (label === '新規レコード追加') {

        element.setAttribute(
          'aria-label',
          'Add New Record'
        );

        return;
      }



      /*
       * Lookup destination field warning
       */

      if (
        label.includes(
          'このフィールドはルックアップフィールドのコピー先に設定されているため、編集できません'
        )
      ) {

        element.setAttribute(
          'aria-label',
          label.replace(
            'このフィールドはルックアップフィールドのコピー先に設定されているため、編集できません',
            'This field cannot be edited because it is configured as a destination field for a Lookup.'
          )
        );

        return;
      }



      /*
       * No edit permission
       */

      if (
        label.includes(
          '編集権限がありません'
        )
      ) {

        element.setAttribute(
          'aria-label',
          label.replace(
            '編集権限がありません',
            'You do not have permission to edit'
          )
        );

        return;
      }



      /*
       * Filtered result accessibility message
       *
       * Example:
       *
       * 検索条件により 1 件に絞り込み中
       * （絞り込み前は全 1,364 件）
       *
       * becomes:
       *
       * Filtered to 1 record by search criteria
       * (1,364 total records before filtering)
       */

      const filterMatch = label.match(
        /検索条件により\s*([\d,]+)\s*件に絞り込み中（絞り込み前は全\s*([\d,]+)\s*件）/
      );


      if (filterMatch) {

        const filteredCount = filterMatch[1];
        const totalCount = filterMatch[2];

        const filteredNumber = Number(
          filteredCount.replace(/,/g, '')
        );


        element.setAttribute(
          'aria-label',

          `Filtered to ${filteredCount} ${
            filteredNumber === 1
              ? 'record'
              : 'records'
          } by search criteria ` +
          `(${totalCount} total records before filtering)`
        );

      }

    });



    /*
     * ----------------------------------------------------------
     * 6. LOADING MESSAGE
     *
     * プラグインを読み込んでいます
     *
     * becomes:
     *
     * Loading plugin...
     * ----------------------------------------------------------
     */

    document.querySelectorAll(
      '.before-load p'
    ).forEach((element) => {

      if (
        element.textContent.includes(
          'プラグインを読み込んでいます'
        )
      ) {

        element.textContent =
          element.textContent.replace(
            'プラグインを読み込んでいます',
            'Loading plugin...'
          );

      }

    });

  }



  /*
   * ============================================================
   * MUTATION OBSERVER
   * ============================================================
   *
   * RIBBIT dynamically redraws parts of the interface.
   * Re-run the translation whenever new elements are added.
   * ============================================================
   */

  let translationScheduled = false;


  const observer = new MutationObserver(() => {

    /*
     * Prevent many simultaneous RIBBIT DOM changes from
     * causing the translation function to run repeatedly.
     */

    if (translationScheduled) {
      return;
    }


    translationScheduled = true;


    requestAnimationFrame(() => {

      translationScheduled = false;

      replaceJapanesePluginText();

    });

  });



  observer.observe(
    document.body,
    {
      childList: true,
      subtree: true
    }
  );



  /*
   * ============================================================
   * INITIAL TRANSLATION
   * ============================================================
   */

  replaceJapanesePluginText();

})();
